version: "3.7"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  ffmpeg:
    image: jrottenberg/ffmpeg:4.1-alpine
    command: >
      -re -i https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8
      -c:v libx264 -preset veryfast -maxrate 1984k -bufsize 3968k
      -c:a aac -b:a 128k -ac 2
      -f flv rtmp://nginx:1935/live/stream
