version: "3.7"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/hls
  ffmpeg:
    build: .
    depends_on:
      - nginx
    restart: unless-stopped
    volumes:
      - /tmp/hls:/hls
