version: "3.7"

services:
  server:
    build: ./server
    ports:
      - "443:8000"
    volumes:
      - /tmp/hls:/tmp/hls
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  stream:
    build: ./stream
    restart: unless-stopped
    volumes:
      - /tmp/hls:/tmp/hls
      - /usr/local/bin/logs:/usr/local/bin/logs
    networks:
      - app-network
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
