version: "3.7"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - "8080:80"
      - "1935:1935"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/hls
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
  ffmpeg:
    build: .
    depends_on:
      - nginx
    restart: unless-stopped
    volumes:
      - /tmp/hls:/hls
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
