version: "3.7"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - "8080:80"
      - "1935:1935"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/hls
    networks:
      - app-network
  ffmpeg:
    build: .
    depends_on:
      - nginx
    restart: unless-stopped
    volumes:
      - /tmp/hls:/hls
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
