version: "3.7"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/tmp/hls
  ffmpeg:
    build: .
    depends_on:
      - nginx
    restart: unless-stopped
    volumes:
      - /tmp/hls:/tmp/hls
  hls-server:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /tmp/hls:/usr/share/nginx/html/hls:ro
      - ./player:/usr/share/nginx/html:ro
    restart: unless-stopped
