version: "3.7"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - "80:80"
      - "1935:1935"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/tmp/hls
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    logging:
      driver: "local"
      options:
        max-size: "10m"

  ffmpeg:
    build: .
    restart: unless-stopped
    volumes:
      - /tmp/hls:/tmp/hls
    networks:
      - app-network
    logging:
      driver: "local"
      options:
        max-size: "10m"

networks:
  app-network:
    driver: bridge
