version: "3.7"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/tmp/hls
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network

  ffmpeg:
    build: .
    restart: unless-stopped
    volumes:
      - /tmp/hls:/tmp/hls
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
